P2022 444
intive/patronage22-java-szczecin pull request #11
Opened 2022-01-27 16:49 UTC by Szachista

2022-01-28 07:30 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private String state;
Here, an existing Enum should be used for the board state (instead of string with pattern).

2022-01-28 07:50 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private String name;
Please use @Column annotation with properties like, name and length istead of @Size.
Here you can find more information about differences: https://www.baeldung.com/jpa-size-length-column-differences

2022-01-28 07:53 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +@Entity
Missing @Table annotation in every model

2022-01-28 07:58 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +@Data
You should avoid using @Data in entity class. Here's an explanation why: https://dzone.com/articles/lombok-and-jpa-what-may-go-wrong

2022-01-28 10:23 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private String state;
Corrected.

2022-01-28 10:23 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private String name;
Corrected.

2022-01-28 10:23 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +@Entity
Corrected.

2022-01-28 10:24 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +@Data
Corrected.

2022-02-01 18:23 UTC, edych approved these changes

2022-02-02 07:16 UTC, patrykzawadzkiintive requested changes

2022-02-02 07:16 UTC, patrykzawadzkiintive commented on src/main/resources/db/migration/V2_0__init.sql
> +    id INT,
Mark that id field as SERIAL, http://sqlines.com/postgresql/datatypes/serial

2022-02-02 07:16 UTC, patrykzawadzkiintive commented on src/main/resources/db/migration/V2_0__init.sql
> +CREATE TABLE IF NOT EXISTS BoardsUsers (
Creation of this table will be no longer required. It will be handled by Hibernate.

2022-02-02 20:07 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/BoardsUsers.java
> +package com.intive.patronage22.szczecin.retroboard.model;
Corrected (I hope so).

2022-02-02 20:07 UTC, Szachista commented on src/main/resources/db/migration/V2_0__init.sql
> +    id INT,
Corrected.

2022-02-02 20:08 UTC, Szachista commented on src/main/resources/db/migration/V2_0__init.sql
> +CREATE TABLE IF NOT EXISTS BoardsUsers (
Corrected (I hope so).

2022-02-03 06:35 UTC, patrykzawadzkiintive approved these changes

2022-02-03 07:39 UTC, golldfish approved these changes

2022-02-03 13:34 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +@Table
As mentioned in the article I pasted earlier, the table name in the @Table annotation is the minimum that should be added.

2022-02-03 13:42 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    @Column(length = 32, nullable = false)
The same problem as for @Table annotation.

2022-02-03 13:43 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private EnumStateDto state;
Here should be @Enumrated annotation.
Please read again carefully this article: https://www.baeldung.com/jpa-entities

2022-02-04 08:15 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private EnumStateDto state;
The last but one sentence before conclusion:

> Actually, we don't have to specify the @Enumerated annotation at all if we are going to persist the Gender by the enum‘s ordinal.

Should I use default value?

2022-02-04 08:30 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +@Table
Done.

2022-02-04 08:30 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    @Column(length = 32, nullable = false)
Done.

2022-02-04 08:31 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private EnumStateDto state;
Good point. Yes default value should be "CREATED" .

2022-02-04 09:37 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    private EnumStateDto state;
I meant "should I use @Enumerated(EnumType.ORDINAL)" :)

2022-02-04 09:41 UTC, daniel-kmiecik approved these changes

2022-02-04 09:45 UTC, merged