Checkstyle implementation
intive/patronage22-java-szczecin pull request #12
Opened 2022-02-03 15:31 UTC by MaciejJ0

2022-02-04 07:35 UTC, patrykzawadzkiintive commented
Changes look correct. But Docker is not able to build container because of missing checkstyle.xml 
![image](https://user-images.githubusercontent.com/95465602/152489787-439af86a-d32d-42c9-9ec5-660d082c065e.png)

Check Dockerfile and do the similiar thing as it is done for pom.xml.

2022-02-04 07:36 UTC, patrykzawadzkiintive requested changes
Check why build has failed and fix it.

2022-02-04 19:39 UTC, edych approved these changes

2022-02-05 10:55 UTC, Radenzvous approved these changes

2022-02-05 14:49 UTC, Szachista approved these changes

2022-02-05 15:22 UTC, MaciejJ0 commented
> 
bug fixed

2022-02-05 17:13 UTC, golldfish approved these changes

2022-02-06 08:16 UTC, patrykzawadzkiintive approved these changes

2022-02-06 08:17 UTC, patrykzawadzkiintive commented
@MaciejJ0 zrób rebase. Jako ze w miedzyczasie zmergowane zostaly zmiany @Szachista to jego klasy tez bedziesz musial poprawic "checkstylem". Jak sie tylko zbuduje to merguj :)

2022-02-06 15:01 UTC, merged