Modify GET request to receive user's boards
intive/patronage22-java-szczecin pull request #14
Opened 2022-02-05 14:46 UTC by Szachista

2022-02-06 12:18 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        Board b2 = new Board();
Can we have the same naming convention as for users?  board1, board2

2022-02-06 15:33 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +@Transactional
Better to use @Transactional for methods

2022-02-06 15:33 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
>      }
It is better to move the logic to the server and return "OK". 
Other answers will be in ControllerAdvice.

2022-02-07 09:17 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +@Transactional
Done.

2022-02-07 09:17 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        Board b2 = new Board();
Done.

2022-02-07 09:20 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
>      }
Probably done.

2022-02-08 08:08 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDto.java
> +@Data
I wanted to use ModelMapper - it requires setters. What is a better way to map model to dto?

2022-02-08 12:02 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/ControllerAndServiceIntegrationTest.java
> +    @MockBean private UserRepository userRepository;
In the WebMvcTest I cannot use userRepository, so I made it in the BoardControllerTest (annotated with SpringBootTest).

2022-02-08 13:09 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @Autowired
Restored with @RequiredArgsConstructor

2022-02-08 13:09 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +    @Autowired
Done.

2022-02-08 13:09 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        User u = userRepository.findById(uid).orElse(null);
Done.

2022-02-08 13:09 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user1 = new User();
Done.

2022-02-08 20:08 UTC, Radenzvous approved these changes

2022-02-09 08:30 UTC, patrykzawadzkiintive requested changes

2022-02-09 08:30 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
>      @GetMapping
Please add something like that:
@ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Ok"),
            @ApiResponse(responseCode = "404", description = "User boards not found")
    })

2022-02-09 08:30 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +    public List<BoardDto> getUserBoards(String uid) {
I think this method should just return user boards, i mean Optional<List<BoardDto>>. If optional will be empty then it means user not exist. 

Throwing exception here is kind of mixing responsibilities of controller & service. Service has it owns logic which could be then reused by other services. Move that exception part to controller class.

2022-02-09 11:37 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
>      @GetMapping
Done.

2022-02-09 12:10 UTC, patrykzawadzkiintive approved these changes

2022-02-09 13:58 UTC, golldfish approved these changes

2022-02-09 14:22 UTC, MaciejJ0 approved these changes

2022-02-10 08:51 UTC, merged

2022-02-10 14:13 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    public static BoardDto toDto(Board board) {
This method should be moved to the BoardDto class.

2022-02-10 14:24 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user1 = makeUser("def","Test user 1");
There's a bit of a mess here. First you create one user, then boards and then users again. You should create all users first, and then save them all to the repository with the "saveAll" method. Finally, you can add users to the boards.

2022-02-10 17:41 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    private User makeUser(String uid, String name) {
Done.

2022-02-10 17:47 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    public static BoardDto toDto(Board board) {
Done.

2022-02-10 17:47 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +            @RequestParam(name = "userId", required = false) String uid) {
Done.