P2022-448
intive/patronage22-java-szczecin pull request #15
Opened 2022-02-06 23:56 UTC by edych

- Added new dependencies: Spring Security and Java JWT
- Provided a postman collection 
- Created new Controller for auth related operations
- "/private" can be only accessed with JWT token
- "/public" can be accessed without logging in
- "/register" for register a new Spring User 
- There is also "/login" (default endpoint for Spring Security) 
- After successfully logging in User receives a JWT token 
- Added UsernameTakenException for situations when we are trying to register a User with username that already exists
- Added Authentication and Authorization filters
- Added Security Configuration 
- Added integration Tests for SecuredController

2022-02-08 13:21 UTC, Szachista submitted a review, later dismissed

2022-02-08 13:50 UTC, patrykzawadzkiintive requested changes

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +        UserDetails preparedUser = User.withUsername(username)
This logic should be moved to new class like UserService.

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/UsernameTakenException.java
> +@ResponseStatus(value= HttpStatus.CONFLICT, reason = "user should not exist")
Better message: User already exist.

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on postman_collection.json
> +{
Please move that file to separate direcotry /postman

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldGiveAccessWhenGettingPublicEndpointWithoutAccessToken() throws Exception {
public_should_return_ok_when_user_annonymous

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldNotGiveAccessWhenGettingPrivateEndpointWithoutAccessToken() throws Exception {
private_should_return_forbidden_when_user_not_logged_in

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldReturnInJSONsBodyCreatedUserIfItDoesNotExistBefore() throws Exception {
register_should_return_json_body_with_created_user_data_when_user_not_exist_before

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldReturnConflictExceptionIfUserExists() throws Exception {
register_should_return_confilct_when_user_not_exist

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldReturnAccessTokenWhenLoggingInIfUserExists() throws Exception {
login_should_return_access_token_when_user_credentials_are_correct

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldReturnUnauthorizedWhenLoggingInIfUserDoesNotExist() throws Exception {
login_should_return_unauthorized_when_user_not_exist

2022-02-08 13:50 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +    void shouldGiveAccessWhenGettingPrivateEndpointWithCorrectAccessToken() throws Exception {
private_should_return_ok_when_user_authenticated

2022-02-08 13:51 UTC, patrykzawadzkiintive commented
Try to add final to variables & method parameters wherever you can.

2022-02-08 14:38 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +        UserDetails preparedUser = User.withUsername(username)
Hi! In this case, should I also write unit tests for UserService? Please let me know, thank you :)

2022-02-09 07:24 UTC, daniel-kmiecik commented on checkstyle.xml
> +        <property name="max" value="120"/>
I just want to mention that if you are working with a group of people, you should discuss changes that will affect the whole team (before you make them) ;)

2022-02-09 07:26 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filer/CustomAuthenticationFilter.java
> +        final String username = request.getParameter("username");
Both "username" and "password should be passed as an environment variable.

2022-02-09 07:33 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filer/CustomAuthorizationFilter.java
> +                    response.setHeader("error", exception.getMessage());
Why do you put this in header?
It's unneccessary when you are passing an error message into response object

2022-02-09 07:48 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filer/CustomAuthorizationFilter.java
> +                    new ObjectMapper().writeValue(response.getOutputStream(), error);
Spring creates default ObjectMapper, so there's no need to create a new instance. Just try to autowire objectmapper in this class. Should work until you need to customize it.

2022-02-09 10:34 UTC, edych commented on checkstyle.xml
> +        <property name="max" value="120"/>
Of course, you are absolutely right. Then maybe let's talk about it all together at our call today? :)

2022-02-09 12:11 UTC, patrykzawadzkiintive submitted a review, later dismissed

2022-02-09 14:05 UTC, golldfish submitted a review, later dismissed

2022-02-09 14:13 UTC, daniel-kmiecik commented on postman/postman_collection.json
> +{
Why do you want to commit this file to the repo? It's something like additional tool, it's not a part of our service.

2022-02-09 14:14 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +public class SecuredController {
The name of the class should refer to its business logic.

2022-02-09 14:44 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/UsernameTakenException.java
> +    public UsernameTakenException() {
It should take a message parameter or a static message variable to be passed to the super() constructor.
Now we don't know what is the cause of the exception.

2022-02-09 14:56 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +                        .contentType(MediaType.APPLICATION_FORM_URLENCODED))
Our controllers should produces JSON format.

2022-02-09 17:18 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +    @GetMapping("/public")
Currently, the public endpoint is /boards, so we do not need another one only for tests. Correct me if I am wrong.

2022-02-09 17:19 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +                .andExpect(status().isConflict());
You also should verify the message of the error.

2022-02-10 23:23 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filer/CustomAuthorizationFilter.java
> +                    new ObjectMapper().writeValue(response.getOutputStream(), error);
done

2022-02-10 23:24 UTC, edych commented on postman/postman_collection.json
> +{
deleted

2022-02-10 23:24 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +public class SecuredController {
renamed

2022-02-10 23:24 UTC, edych commented on postman/postman_collection.json
> +{
done

2022-02-10 23:24 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +public class SecuredController {
done

2022-02-10 23:25 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/UsernameTakenException.java
> +public class UsernameTakenException extends RuntimeException {
yes :) done

2022-02-10 23:25 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/UserService.java
> +        if (userExists(username)) {
done

2022-02-10 23:26 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredController.java
> +    @GetMapping("/public")
correct. I have deleted this enpoint

2022-02-10 23:27 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +                .andExpect(status().isConflict());
done

2022-02-10 23:29 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/SecuredControllerTest.java
> +                        .contentType(MediaType.APPLICATION_FORM_URLENCODED))
done

2022-02-11 07:27 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers("/register", "/boards", "/public").permitAll();
There's no more "/public" endpoint.

2022-02-11 07:30 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/UserService.java
> +    private boolean userExists(final String username) {
Methods which return boolean should start with "is". In this case should be "isUserExist".

2022-02-11 07:33 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/UserService.java
> +    private boolean userExists(final String username) {
isUserExisting (?)

2022-02-11 08:27 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers("/register", "/boards", "/public").permitAll();
Sorry, I've missed that. Done

2022-02-11 08:32 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/UserService.java
> +    private boolean userExists(final String username) {
done

2022-02-11 08:41 UTC, golldfish approved these changes

2022-02-11 08:50 UTC, daniel-kmiecik approved these changes

2022-02-11 09:09 UTC, merged