Create new board for user id
intive/patronage22-java-szczecin pull request #17
Opened 2022-02-07 11:59 UTC by MaciejJ0

2022-02-08 13:15 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDto.java
>      String id;
This should be an Integer.

2022-02-08 21:17 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDto.java
>      String id;
Done

2022-02-08 22:23 UTC, edych approved these changes

2022-02-09 11:50 UTC, Szachista approved these changes

2022-02-09 14:02 UTC, golldfish approved these changes

2022-02-10 06:40 UTC, patrykzawadzkiintive requested changes

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +        return boardService.saveBoardForUserId(nameBoard.getName(), userId);
During creation of board, user should not be able to specify the board state. It should be automatically set to EnumState.CREATED

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDto.java
> -    String id;
Can you add @ApiModelProperty(value = "Board id", required = "false", example = "1") for each of those fields?

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardNameDTO.java
> +
Can you add @ApiModelProperty(value = "Board name", required = "true", example = "1")

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/User.java
> +    public User(String uid, String name) {
Why this is required? You allready hava AllArgConstructor so you could initialize object like new User(uid,name, Set.of());

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/model/Board.java
> +    public Board(String name, User creator) {
Why this is required? You allready hava AllArgConstructor so you could initialize object like new Board(id,name,state, creator, Set.of());

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +    public BoardDto saveBoardForUserId(String boardName, String userId) {
Please rename that to createNewBoard

2022-02-10 06:40 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +    public BoardDto saveBoardForUserId(String boardName, String userId) {
During creation of board, user should not be able to specify the board state. It should be automatically set to EnumState.CREATED

2022-02-10 06:40 UTC, patrykzawadzkiintive commented
Try to use final wherever you can, in methods & arguments etc.

2022-02-10 07:58 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    public BoardDto createNewBoardForUserId(@RequestParam String userId,
createNewBoard is a sufficient name. The Arguments method tells you what is needed to do this ;)

2022-02-11 09:07 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        Board newBoard = new Board(boardName, user);
Please mark variables as final.

2022-02-11 09:09 UTC, daniel-kmiecik commented on src/main/resources/db/migration/V1_2__add_initial_user.sql
> +INSERT INTO User VALUES ('uid1', 'John');
Please add TODO comment: It must be deleted when the test db is created.

2022-02-11 09:10 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    void userAlreadyExists_shouldReturnStatus201() throws Exception {
Please use one naming convention instead of two in the method name.

2022-02-11 09:13 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    void userAlreadyExists_shouldReturnStatus201() throws Exception {
Bad method name. It suggests that controller returns status 201 when user already exists.

2022-02-11 09:16 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/ControllerAndServiceIntegrationTest.java
>  public class ControllerAndServiceIntegrationTest {
Please rename this class to match the class you are testing (BoardController).

2022-02-11 09:17 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/ControllerAndServiceIntegrationTest.java
> +    @Autowired private MockMvc mvc;
Incorrect formatting. The annotation should be above the variable.

2022-02-11 09:19 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +@SpringBootTest
It's not neccessary to load SprinBoot context here.
Using @RunWith(MockitoJUnitRunner.class) should be enough to test this functionality.

2022-02-15 19:48 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +                "/h2-console/**").permitAll();
the other PR is removing h2 db, should this still be here?

2022-02-15 20:03 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +                "/h2-console/**").permitAll();
The master still has h2

2022-02-15 22:34 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                                   @RequestBody final BoardCreateDto nameBoard) {
I'd rename this to final BoardCreateDto boardName, newBoardData/newBoardName or boardCreateDto

2022-02-15 22:34 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final Board save = boardRepository.save(newBoard);
I think you don't need to create object save. Maybe put return BoardDto.mapToDto(boardRepository.save(newBoard)) instead of creating object.

2022-02-16 07:24 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final Board save = boardRepository.save(newBoard);
done

2022-02-16 07:26 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                                   @RequestBody final BoardCreateDto nameBoard) {
done

2022-02-16 14:32 UTC, patrykzawadzkiintive requested changes

2022-02-16 14:32 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> -    public void whenUserHasTwoBoardsThenBodyShouldContainTwoBoards() {
Why do you remove that test?

2022-02-16 14:32 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/ControllerAndServiceIntegrationTest.java
> -package com.intive.patronage22.szczecin.retroboard.controller;
Why did you removed that test class?

2022-02-16 14:32 UTC, patrykzawadzkiintive commented on pom.xml
> +        <dependency>
Please remove that dependency, it will be no longer required.

2022-02-16 16:27 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/ControllerAndServiceIntegrationTest.java
> -package com.intive.patronage22.szczecin.retroboard.controller;
I moved tests to BoardController

2022-02-16 22:10 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDto.java
> +    @ApiModelProperty(value = "Board id", name = "id", example = "1")
done

2022-02-16 22:10 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @PostMapping
done

2022-02-16 22:10 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
>              @ApiResponse(responseCode = "400", description = "Bad request data"),
done

2022-02-16 22:15 UTC, edych approved these changes

2022-02-17 06:39 UTC, patrykzawadzkiintive approved these changes

2022-02-17 09:07 UTC, edych approved these changes

2022-02-17 09:12 UTC, Szachista approved these changes

2022-02-17 12:10 UTC, merged