P2022 1013
intive/patronage22-java-szczecin pull request #24
Opened 2022-02-18 20:56 UTC by Szachista

I was unable to make login test - could somebody tell me, how to mock AuthenticationManager?

2022-02-19 10:43 UTC, patrykzawadzkiintive requested changes
Add final wherever you can ;)

2022-02-19 10:43 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +        final RestTemplate restTemplate = new RestTemplate();
Extract RestTemplate as separate bean. Creation of restTemplate is expensive operation.  
https://howtodoinjava.com/spring-boot2/resttemplate/spring-restful-client-resttemplate-example

Extracting RestTemplate as separate bean allow you to test mock responses in unit test.

2022-02-19 10:43 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthenticationFilter.java
> +        final String email = request.getParameter("email");
What will happened if email and/or password is null or blank? Do we need additional validation?

2022-02-19 10:43 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +                    "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=" + apiKey,
Could you extract this url as private static final String? It's better to reuse it instead of creatin it every time method is invoked.

2022-02-19 10:43 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +//    @Test
Why this test is commented? Extract RestTemplate as separate bean and mock response here this will allow you tp test all cases like Wrong password, success etc.

2022-02-19 10:43 UTC, patrykzawadzkiintive commented on pom.xml
>                      </excludes>
Maybe thos exclusion won't be required if you test those classes with mocking rest template.

2022-02-19 10:43 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/UserDto.java
> +public class UserDto {
Please rename that dto to FirebaseUserDto

2022-02-19 13:50 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthenticationFilter.java
> +        final String email = request.getParameter("email");
Good point. Should this validation happen here or in the CustomAuthenticationFilter?

2022-02-19 13:52 UTC, Szachista commented on pom.xml
>                      </excludes>
FirebaseAuthenticationProvider (rather) must be, FirebaseUserDto maybe not.

2022-02-19 16:10 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/UserDto.java
> +public class UserDto {
Done.

2022-02-19 16:10 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +//        auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder);
Done.

2022-02-19 16:11 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +//    private final UserDetailsService userDetailsService;
Done.

2022-02-19 16:11 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/SecurityConfig.java
> +    @Primary
Done.

2022-02-19 20:50 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/FirebaseUserDto.java
> +    private boolean registered;
Add @Schema above the variables

2022-02-19 20:50 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/UserLoginRequestDto.java
> +    private final boolean returnSecureToken = true;
Add @Schema above the variables

2022-02-20 08:43 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/FirebaseUserDto.java
> +    private boolean registered;
Actually I'm not sure whether it is necessary. This class is not used outside.

2022-02-20 08:43 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/UserLoginRequestDto.java
> +    private final boolean returnSecureToken = true;
Same as above.

2022-02-20 10:23 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthenticationFilter.java
> +        final String email = request.getParameter("email");
In custom authentication filter please

2022-02-21 09:57 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthenticationFilter.java
> +        final String email = request.getParameter("email");
Done.

2022-02-21 09:57 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +//    @Test
Tests are fixed.

2022-02-21 11:11 UTC, patrykzawadzkiintive requested changes

2022-02-21 11:11 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/FirebaseUserDto.java
> +    private boolean registered;
No it's not required. It's not returned to the end user.

2022-02-21 11:11 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/UserLoginRequestDto.java
> +    private final boolean returnSecureToken = true;
No it's not required. It's not returned to the end user.

2022-02-21 11:11 UTC, patrykzawadzkiintive commented on pom.xml
> +                        <exclude>com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.class</exclude>
These exclusions could be removed.

2022-02-21 11:11 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +            } catch(JsonProcessingException e1) {
final

2022-02-21 11:11 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +        } catch (RestClientResponseException e) {
final

2022-02-21 11:11 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +package com.intive.patronage22.szczecin.retroboard.provider;
Set "final" in class variables, exceptions, inputs etc :)

2022-02-21 11:56 UTC, Szachista commented on pom.xml
> +                        <exclude>com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.class</exclude>
Done.

2022-02-21 11:56 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +            } catch(JsonProcessingException e1) {
Done.

2022-02-21 11:57 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +        } catch (RestClientResponseException e) {
Done.

2022-02-21 12:27 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +    private final String firebaseUrl = "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=";
Should be available from the property file.

2022-02-21 12:31 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +    private final String firebaseUrl = "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=";
Which one? Should I put firebaseUrl to the application.yml only?

2022-02-21 14:43 UTC, daniel-kmiecik approved these changes

2022-02-21 16:26 UTC, patrykzawadzkiintive approved these changes

2022-02-21 18:24 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/provider/FirebaseAuthenticationProvider.java
> +    private final String firebaseUrl = "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=";
I will create task for that.

2022-02-21 18:24 UTC, merged