P2022-1007 Add validation to board creation.
intive/patronage22-java-szczecin pull request #26
Opened 2022-02-19 21:29 UTC by edych

When user creates new board "name" is required and should not be blank or null

- Changed UserValidator name to FormatValiator
- Added new validation method isBoardNameValid which checks if boardName is not blank, empty or null
- Added new BoardNameFormatException, results with 400 Bad Request error code
- Updated BoardService with boardName validation
- Adjusted tests for current application state

2022-02-20 10:07 UTC, patrykzawadzkiintive requested changes

2022-02-20 10:07 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/validation/FormatValidator.java
> +    public static boolean isBoardNameValid(final String boardName) {
Above method do the same hasText() can you reuse it?

2022-02-20 10:07 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +                        .content("{\"name\":\"" + boardName + "\"}")
What will happened if ther will be something like serialized null in json ex. "name":null

2022-02-20 10:07 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                    @ApiResponse(responseCode = "400", description = "BoardName cannot be empty")})
Board name instead of boardName.

2022-02-20 10:09 UTC, patrykzawadzkiintive commented
Your validators are correct. But there is also easier way to do that , you cold try that under this PR or in the future if you want ;)

https://reflectoring.io/bean-validation-with-spring-boot/
https://www.baeldung.com/spring-boot-bean-validation

2022-02-21 10:51 UTC, Szachista submitted a review, later dismissed

2022-02-21 10:51 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/BoardNameFormatException.java
> +@ResponseStatus(value = HttpStatus.BAD_REQUEST, reason = "BoardName cannot be empty")
The same typo (BoardName), as Patryk pointed it earlier.

2022-02-21 10:51 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
>                  .orElseThrow(UserNotFoundException::new);
Daniel told Marcin: "Try to keep the logic about the user in a class designed for it (UserService).
I mean that "user's stuff" should be done in UserService." Maybe UserService could have "getUser" method.

2022-02-21 11:17 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
>                  .orElseThrow(UserNotFoundException::new);
Hi, shouldn't we create new UserService and the current rename to for example FirebaseUserService? @daniel-kmiecik  should I change the code which I didn't add and wasn't connected to the current task?

2022-02-21 14:55 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
>                  .orElseThrow(UserNotFoundException::new);
@Szachista  is right, but I mentioned it in another PR, so let it stay as is here. Someone else will change it in another PR.

2022-02-21 23:48 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +                        .content("{\"name\":\"" + boardName + "\"}")
I have deleted FormatValidator class. Instead of using this validator, I'm using validation with spring

2022-02-21 23:49 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/validation/FormatValidator.java
> +    public static boolean isBoardNameValid(final String boardName) {
I have deleted the FormatValidation class. Instead of using this validator, I'm using spring validation

2022-02-22 17:09 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +                        .content("{\"name\":\"" + boardName + "\"}")
It will return Bad Request. I have created test for this case in BoardControllerTest "createNewBoardShouldReturnBadRequestWhenBoardNameIsNull"

2022-02-22 17:10 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                    @ApiResponse(responseCode = "400", description = "BoardName cannot be empty")})
done

2022-02-22 17:11 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/BoardNameFormatException.java
> +@ResponseStatus(value = HttpStatus.BAD_REQUEST, reason = "BoardName cannot be empty")
I have deleted this exception

2022-02-22 20:59 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCreateDto.java
> +    @NotBlank
@NotEmpty also includes @NotNull

2022-02-22 21:19 UTC, daniel-kmiecik approved these changes

2022-02-23 10:03 UTC, patrykzawadzkiintive approved these changes

2022-02-23 10:17 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/UserAlreadyExistException.java
> +        super(message);
I moved @ResponseStatus to ExceptionHandlerService (userAlreadyExistsHandler()), it returns 409

2022-02-23 10:20 UTC, patrykzawadzkiintive approved these changes

2022-02-23 10:41 UTC, golldfish approved these changes

2022-02-23 11:27 UTC, merged