Added delete board api
intive/patronage22-java-szczecin pull request #27
Opened 2022-02-20 12:55 UTC by msperski

2022-02-20 20:49 UTC, patrykzawadzkiintive requested changes

2022-02-20 20:49 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                                   @RequestParam(name = "boardId") final int bid) {
Can you rename that to boardId. bid is not clear name

2022-02-20 20:49 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @DeleteMapping("/{bid}")
Can you rename that to boardId

2022-02-20 20:49 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/BoardNotFoundException.java
> +    public BoardNotFoundException() {
Can you double chceck if ther isn't any similiar exception already in our repo.

2022-02-20 20:49 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void deleteBoardShouldReturnNotFoundWhenBoardOrUserNotExist(){
Can you create other tests for success dletion, user dele board not created by him, board does not exist etd

2022-02-21 09:28 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                                   @RequestParam(name = "boardId") final int bid) {
"bid" is not a request param. It's a PathParam.
Look at the differeneces here: https://www.baeldung.com/spring-requestparam-vs-pathvariable

2022-02-21 09:28 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @Operation(summary = "Delete retro board for given user.",
Should be "delete retro board for given **id**"

2022-02-21 09:29 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +            responses = {@ApiResponse(responseCode = "200", description = "Board deleted for given user"),
Description same as above

2022-02-21 09:30 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                    @ApiResponse(responseCode = "400", description = "User is not the owner"),
Better will be "User is not the **board** owner"

2022-02-21 09:54 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    public void deleteNewBoard(@RequestParam(name = "userId") final String uid,
Why have you added "new" in the method name?
It can simply name "delete". Take into account that we are in the BoardController, so each operation in this class is related to the board.

2022-02-21 09:57 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final User user = userRepository.findById(uid)
Try to keep the logic about the user in a class designed for it (UserService).
I mean that "user's stuff" should be done in UserService.

2022-02-21 10:01 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +                    "Forbidden request - given user is not creator");
In our database this is the creator, but to the user the creator is simply the owner. And that name is more understable for the user.

2022-02-21 10:27 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND,
Maciej created the ExceptionHandlerService. It's better to have one solution to handle exceptions. Please use this one created by him.
Please familiarize with ControllerAdvice in SpringBoot.

2022-02-21 11:17 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void deleteBoardShouldReturnNotFoundWhenBoardOrUserNotExist(){
This test has not proper name.
if user doesn't exist it will always be UserNotFoundException, so the method name should be "...WhenUserNotExists".
Please add other test cases like mentioned above.

2022-02-23 10:33 UTC, patrykzawadzkiintive requested changes

2022-02-23 10:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final Board board = boardRepository.findById(boardId)
You could do that much easier:
```
  public void delete(final int boardId, final String uid) {
       final Board board = boardRepository.findById(boardId)
                      .orElseThrow(() -> new NotFoundException("Board not found"));

        if(!(uid.equals(board.getCreator().getUid))){
            throw new BadRequestException("User is not owner");
        }else{
            boardRepository.deleteById(boardId);
        }
```

2022-02-23 10:34 UTC, patrykzawadzkiintive commented
Please do the update of your branch with master. Verify if build succeed.

2022-02-23 15:04 UTC, edych commented on .env
> +FIREBASE_CLIENT_ID=102716715859300760037
you probably should revert these changes

2022-02-23 15:16 UTC, edych commented
hello, you should also delete whole directory validation/ including UserValidator.java, it's not in use anymore

2022-02-23 15:28 UTC, golldfish commented
I'm thinking about tests - you didn't cover all lines in delete() method in BoardService. I'd be good to check that if/else statement. Also I'm wondering whether we should have functional tests for removing board to cover controller class.

2022-02-23 15:39 UTC, patrykzawadzkiintive approved these changes

2022-02-23 16:40 UTC, patrykzawadzkiintive requested changes

2022-02-28 12:12 UTC, patrykzawadzkiintive approved these changes

2022-02-28 16:37 UTC, MaciejJ0 approved these changes

2022-02-28 17:04 UTC, edych approved these changes

2022-02-28 17:56 UTC, merged