P2022 1006 - Patch Board
intive/patronage22-java-szczecin pull request #31
Opened 2022-02-22 20:10 UTC by Radenzvous

Added patch functionality with 3 service tests and one controller test

2022-02-22 21:50 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @Operation(summary = "Update board name and # of votes")
What does this "#" means?

2022-02-22 21:51 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    public ResponseEntity<BoardDto> patchBoardData(
Simply "update" as methond name is enough.

2022-02-23 06:22 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @Operation(summary = "Update board name and # of votes")
https://en.wikipedia.org/wiki/Number_sign
I can change it if it is confusing

2022-02-23 10:16 UTC, patrykzawadzkiintive requested changes

2022-02-23 10:16 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    @Operation(summary = "Update board name and # of votes")
Please change that as Daniel suggested.

2022-02-23 10:16 UTC, patrykzawadzkiintive commented on src/main/resources/db/migration/V1_0__init.sql
> +    maximum_number_of_votes INTEGER,
You could set here "NOT NULL default 0"

2022-02-23 10:16 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardNameVotesDto.java
> +@Value
You are validating that data here but unfortunately it's not best solution. This prevent you from updating only one of those parameters. Because both are marked as @NotNull @NotBlank etc. I think here you should not implement any validation, because any of them / both could be null.

2022-02-23 10:16 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +            @RequestBody @Valid final BoardNameVotesDto boardNameVotesDto) {
You should not Validate that (see comment in BoardNameVotesDto class)

2022-02-23 10:16 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardNameVotesDto.java
> +public class BoardNameVotesDto {
Could you rename that class to BoardPatchDto

2022-02-23 10:16 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    void patchBoardShouldReturnNotFoundWhenBoardDoesNotExist() throws Exception {
Can you add test to update board votes only without name?

2022-02-23 15:21 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/BoardNotFoundException.java
> +}
Please don't create exceptions like that - use mine (_NotFoundException_) that is merged to master now and simply pass message in constructor. It'd prevent us from creating eg. 100 not found exceptions with different names.

2022-02-23 15:21 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/exception/NotABoardOwnerException.java
> +}
same as above

2022-02-27 17:11 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +    public ResponseEntity<BoardDto> patchBoardData(
done

2022-02-28 12:18 UTC, patrykzawadzkiintive requested changes

2022-02-28 12:18 UTC, patrykzawadzkiintive commented on src/main/resources/db/migration/V1_0__init.sql
> +    maximum_number_of_votes INTEGER NOT NULL default 0,
This change should be created as separate SQL script. Like V3_0... and it should only alter table with that column.

2022-02-28 12:18 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +            final String message = "Name cannot be blank or null and can be up to 32 characters";
Extract that as private static final String in that class

2022-02-28 12:18 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +            final String message = "Value cannot be above " + Integer.MAX_VALUE + " and value cannot be below 0.";
Extract that as private static final String in that class

2022-02-28 18:33 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +            @RequestBody final BoardPatchDto boardNameVotesDto) {
Variable name should be the same as class name: boardPatchDto. "boardNameVotes" is really strange name.

2022-02-28 18:40 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +public class BoardValidator {
Please use Spring validators

2022-02-28 18:49 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    void patchBoardShouldReturnNotFoundWhenBoardDoesNotExist() throws Exception {
It's not the case Patryk mentioned.

2022-02-28 18:55 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void patchBoardShouldReturnUserIsNotAnOwnerIfTheirUidDoNotMatchBoardOwnerUid() {
The sufficient name for this method is "patchBoardShouldReturnUserIsNotAnOwner"

2022-02-28 18:57 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var boardNameVotesDto = new BoardPatchDto("testboard", 1500);
Please name variables like class names, e.g. boardPatchDto for BoardPatchDto class.

2022-02-28 19:00 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidatorTest.java
> +                new BoardPatchDto
Please add more parameters to the stream.

2022-02-28 19:00 UTC, daniel-kmiecik commented on src/test/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidatorTest.java
> +                ("252435245234524352354234234235235324523452234542353245325432543245235", 0));
Please add more parameters to the stream

2022-03-01 07:02 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +public class BoardValidator {
The whole idea of validator is that any of the parameters could be null, but if it's provided then we want to check if it's valid. Are we able to do that using Spring validators?

2022-03-01 21:18 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Please remove empty lines

2022-03-02 07:42 UTC, patrykzawadzkiintive requested changes

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDto.java
> +
do not leave empty lines on the end of the method

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardPatchDto.java
> +
Do not leave double empty lines.

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +
Do not leave double empty lines. Remove all empty lines on the end of the method

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +
Do not leave double empty lines. Remove all empty lines on the method beginning.

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +
Do not leave empty line here.

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidator.java
> +
Do not leave empty line here.

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidatorTest.java
> +
Do not leave empty lines here.

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidatorTest.java
> +
Do not leave empty lines here.

2022-03-02 07:42 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/validation/BoardValidatorTest.java
> +                ;
Do not leave empty line here. Move ; to line above.

2022-03-02 16:15 UTC, patrykzawadzkiintive approved these changes

2022-03-02 16:58 UTC, edych approved these changes

2022-03-02 17:01 UTC, Szachista approved these changes

2022-03-02 17:34 UTC, merged