Add versioning to the api
intive/patronage22-java-szczecin pull request #35
Opened 2022-02-26 17:21 UTC by MaciejJ0

Added @Slf4j on each controller
Added **/api/v1** to each endpoint

2022-03-01 12:36 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +@RequestMapping(value = "${retroboard.api-version}/boards", produces = MediaType.APPLICATION_JSON_VALUE)
Api version shoudn't be a property.
What if each endpoint has a different version of the api?

2022-03-01 12:36 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +    private String apiVersion;
Api version shoudn't be a property.
What if each endpoint has a different version of the api?

2022-03-01 21:09 UTC, edych approved these changes

2022-03-02 06:44 UTC, patrykzawadzkiintive requested changes

2022-03-02 06:44 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers(URL_REGISTER, "/api/v1/boards/**", URL_LOGIN,
Can you instead of providing each url (REGISTER, LOGIN, BOARDS), just set in filter ` /api/v1/**`

2022-03-02 10:29 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers(URL_REGISTER, "/api/v1/boards/**", URL_LOGIN,
My fault, we are going to remove access to /api/v1/boards/** soon . So leave it as it is.

2022-03-02 10:29 UTC, patrykzawadzkiintive approved these changes

2022-03-02 21:40 UTC, patrykzawadzkiintive approved these changes

2022-03-02 21:41 UTC, merged