P2022 1016 add new users during jwt validation
intive/patronage22-java-szczecin pull request #38
Opened 2022-03-03 21:02 UTC by msperski

2022-03-03 23:21 UTC, golldfish approved these changes

2022-03-04 07:08 UTC, patrykzawadzkiintive requested changes

2022-03-04 07:08 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthorizationFilter.java
> +                    if(userRepository.findUserByEmail(firebaseToken.getEmail()).isPresent())
We don't need both if & else. Just check if user not exist and add it in that case to db + add logger User ${email here} created in database.

2022-03-04 07:08 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    @MockBean
There is no unit test for your logic? Please verify how it would behave if user is in database and how if user is not.

2022-03-04 07:48 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthorizationFilter.java
> +                    if(userRepository.findUserByEmail(firebaseToken.getEmail()).isPresent())
Try to use Optional instaead of isPresent().

2022-03-05 10:26 UTC, Szachista approved these changes

2022-03-05 10:26 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user = new User("123", email, "displayName", Set.of());
final?

2022-03-05 10:26 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthorizationFilter.java
> +                                firebaseToken.getEmail(), firebaseToken.getName(), Set.of());
final?

2022-03-05 10:26 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user = new User("123", "email@email.com", "displayName", Set.of());
final?

2022-03-05 10:26 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user = new User("123", email, "displayName", Set.of());
final?

2022-03-05 10:26 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user = new User("123", "email@email.com", "displayName", Set.of());
final?

2022-03-05 10:26 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user = new User("123", email, "displayName", Set.of());
final?

2022-03-05 10:26 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        User user = new User("123", "email@email.com", "displayName", Set.of());
final?

2022-03-06 10:10 UTC, patrykzawadzkiintive requested changes

2022-03-06 10:10 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthorizationFilter.java
> +                    Optional<User> optionalUser = userRepository.findById(firebaseToken.getUid());
final :)

2022-03-06 10:10 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +    void getUserBoardsShouldReturnOkWhenUserNotExistsInDatabase() throws Exception {
getUserBoardShouldSaveUserAndReturnOkWhenUserNotExistsInDatabase

2022-03-06 10:10 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +                .andExpect(jsonPath("$.*", hasSize(2)));
on the end of the test add check if userRepository.save() is executed.

Use mockito verify() method

2022-03-06 10:10 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +        mockMvc.perform(get(boardDataUrl)
on the end of the test add check if userRepository.save() is not executed.

Use mockito verify() method

2022-03-06 21:15 UTC, edych approved these changes

2022-03-07 07:30 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardControllerTest.java
> +                .andExpect(result -> verify(userRepository, times(0)).save(any()));
Better to use never() instead of times(0)

2022-03-07 07:30 UTC, patrykzawadzkiintive approved these changes

2022-03-07 09:14 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthorizationFilter.java
> +                    final Optional<User> optionalUser = userRepository.findUserByEmail(firebaseToken.getEmail());
You can use ifPresent instead of create "optionalUser" variable.

2022-03-07 12:09 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/filter/CustomAuthorizationFilter.java
> +                    userRepository.findUserByEmail(firebaseToken.getEmail()).ifPresentOrElse(
I'm sorry, my mistake. Please revert the previous version of the code.

2022-03-07 12:16 UTC, daniel-kmiecik approved these changes

2022-03-07 12:23 UTC, merged