patchBoard now validates if board state is other than created and doe…
intive/patronage22-java-szczecin pull request #42
Opened 2022-03-07 21:30 UTC by Radenzvous

…s not allow modification of the maximum number of votes

2022-03-08 06:30 UTC, patrykzawadzkiintive commented
Code looks good, but you need to create a unit test for that. What happened when you update number of votes when board state is created, and what happened if other state.

2022-03-08 06:30 UTC, patrykzawadzkiintive requested changes
Code looks good, but you need to create a unit test for that. What happened when you update number of votes when board state is created, and what happened if other state.

2022-03-08 08:55 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +                                ("Not a board owner!"));
Formatting

2022-03-08 08:55 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +                        ("State of board does not allow to change number of votes!");
Formatting - unnecessary new line

2022-03-09 07:27 UTC, patrykzawadzkiintive requested changes

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
you don't need to create state as separate variable if it's used only in line below
```suggestion
        final var board = buildBoard(user, EnumStateDto.CREATED);
```

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
you don't need to create state as separate variable if it's used only in line below
```suggestion
        final var board = buildBoard(user, EnumStateDto.CREATED);
```

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
you don't need to create state as separate variable if it's used only in line below
```suggestion
        final var board = buildBoard(user, EnumStateDto.CREATED);
```

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
Same as above

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
you don't need to create state as separate variable if it's used only in line below
```suggestion
        final var board = buildBoard(user, EnumStateDto.CREATED);
```

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.VOTING;
you don't need to create state as separate variable if it's used only in line below
```suggestion
        final var board = buildBoard(user, EnumStateDto.CREATED);
```

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
you don't need to create state as separate variable if it's used only in line below
```suggestion
        final var board = buildBoard(user, EnumStateDto.CREATED);
```

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void patchBoardShouldReturnBadRequestWhenBoardStateNotCreated() {
patchBoardShouldReturnBadRequestWhenBoardState**Is**NotCreated

2022-03-09 07:27 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +            }
add empty line to separate that if else from next if

2022-03-09 15:18 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +                                ("Not a board owner!"));
done

2022-03-09 15:18 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +                        ("State of board does not allow to change number of votes!");
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.VOTING;
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var state = EnumStateDto.CREATED;
done

2022-03-09 15:38 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void patchBoardShouldReturnBadRequestWhenBoardStateNotCreated() {
done

2022-03-10 13:32 UTC, patrykzawadzkiintive approved these changes

2022-03-10 13:37 UTC, daniel-kmiecik approved these changes

2022-03-10 14:04 UTC, edych approved these changes

2022-03-10 15:36 UTC, merged