Jacoco
intive/patronage22-java-szczecin pull request #5
Opened 2022-01-24 15:45 UTC by msperski

2022-01-24 21:46 UTC, Radenzvous commented
running .\mvnw clean test jacoco:report
I get 

[INFO] --- jacoco-maven-plugin:0.8.6:report (report) @ retroboard ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.6:report (default-cli) @ retroboard ---
[INFO] Skipping JaCoCo execution due to missing execution data file.

is it expected?

2022-01-25 00:03 UTC, msperski commented
I fixed error it should work now.

2022-01-25 13:18 UTC, patrykzawadzkiintive requested changes

2022-01-25 13:18 UTC, patrykzawadzkiintive commented on pom.xml
> +		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Try to avoid committing just changes in line formatting. Try to remove this change, by comparing this file against "master" branch. and restore old formatting.

2022-01-25 13:18 UTC, patrykzawadzkiintive commented on pom.xml
> +			<version>0.8.7</version>
You don't need to specify version for jacococ. 

Remove that , then spring will automatically apply version from spring BOM https://www.baeldung.com/spring-maven-bom

2022-01-25 18:08 UTC, msperski commented on pom.xml
> +			<version>0.8.7</version>
I get error without specified version. 
![image](https://user-images.githubusercontent.com/95183688/151034041-d34070ab-7189-4655-a32f-01e8e7a315e6.png)

2022-01-26 08:04 UTC, daniel-kmiecik commented on pom.xml
> +			<version>0.8.7</version>
To clarify that. It's not a bug to have a dependency version in a pom file , but the solution that Patryk mentioned is the easiest way to keep dependencies up to date. Marcin, please read the whole article that Patryk linked. There's also link to the gitlab example. Just read and decide which way we should go.

2022-01-26 10:21 UTC, patrykzawadzkiintive commented on pom.xml
> +			<version>0.8.7</version>
As Daniel said it's up to you :)

2022-01-26 12:03 UTC, MaciejJ0 approved these changes

2022-01-26 16:35 UTC, patrykzawadzkiintive approved these changes

2022-01-26 17:43 UTC, Szachista approved these changes

2022-01-26 17:50 UTC, golldfish approved these changes

2022-01-26 18:46 UTC, merged