P2022-1429 Change the exception message type to JSON
intive/patronage22-java-szczecin pull request #52
Opened 2022-03-11 17:35 UTC by MaciejJ0

2022-03-11 17:57 UTC, golldfish requested changes

2022-03-11 17:57 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/advice/ExceptionHandlerService.java
> +
Please remove empty lines

2022-03-11 20:14 UTC, Szachista approved these changes

2022-03-11 20:26 UTC, edych approved these changes

2022-03-11 22:52 UTC, msperski approved these changes

2022-03-12 07:49 UTC, golldfish approved these changes

2022-03-12 09:03 UTC, patrykzawadzkiintive approved these changes

2022-03-12 09:03 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/ErrorResponse.java
> +    public static ErrorResponse buildErrorResponse(Exception exception) {
final

2022-03-12 09:03 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/ErrorResponse.java
> +    public static ErrorResponse buildErrorResponse(FieldError fieldError) {
final

2022-03-12 09:24 UTC, Radenzvous approved these changes

2022-03-12 11:57 UTC, merged