Added deleting user assigned to board, tests
intive/patronage22-java-szczecin pull request #53
Opened 2022-03-11 22:12 UTC by msperski

2022-03-12 00:53 UTC, edych approved these changes

2022-03-12 07:47 UTC, golldfish requested changes

2022-03-12 07:47 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +            throw new BadRequestException("User can't delete board");
But why do you throw ‘User can’t delete board’? I believe this case is about removing user from the board and not the board itself.

2022-03-12 07:47 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void removeAssignedUserShouldThrowNotFoundWhenUserOrBoardAreNotExist(){
In this test you only check whether user does not exists, not the board. You can simplify this test:
`when(userRepository.findById(user.getUid())).thenReturn(Optional.empyty()));`

2022-03-12 07:47 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void removeAssignedUserShouldThrowBadRequestWhenUserIsBoardOwner(){
Isn't this test the same as removeAssignedUserShouldThrowBadRequestWhenBoardOwnerTriesToSelfDelete?

2022-03-12 07:47 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
What with case when user is not a board owner and tried to self delete (when it's assigned to board)?

2022-03-12 07:47 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
please remove empty line

2022-03-12 17:32 UTC, patrykzawadzkiintive requested changes

2022-03-12 17:32 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    @DisplayName("removeAssignedUserShouldThrowNotFoundWhenUserNotExists should throw Not Found")
If you using display name, then write display name in more redable waw. Ex. "Remove assigned user .."

Do that also with other methods.

2022-03-12 17:32 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        if(email.equals(user.getEmail()) || email.equals(board.getCreator().getEmail())){
if () space between if and the bracket

2022-03-12 17:32 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +            throw new BadRequestException
} else {

2022-03-12 21:17 UTC, patrykzawadzkiintive approved these changes

2022-03-13 16:23 UTC, MaciejJ0 approved these changes

2022-03-13 19:47 UTC, Radenzvous approved these changes

2022-03-14 06:47 UTC, Szachista approved these changes

2022-03-14 07:11 UTC, golldfish approved these changes

2022-03-14 09:19 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        if (email.equals(user.getEmail()) || email.equals(board.getCreator().getEmail())) {
Are you sure that email is not null?

2022-03-14 11:40 UTC, merged