P2022-1279 Add card to the board.
intive/patronage22-java-szczecin pull request #55
Opened 2022-03-13 20:28 UTC by edych

- In BoardCard I had to set BoardCardsColumn `@Column` name from "column" to "board_column", because as I tried to persist BoardCard to the db I recieved an error: 

```
SQL Error: 0, SQLState: 42601
ERROR: syntax error at or near "column"

Error logging in Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernateexception.SQLGrammarException: could not execute statement
```

I believe we were using PostgreSQL reserved keyword "column"

- Added migration file (renamed column "column" to board_column in table retro.board_card)
- Added new Controller for BoardCards and tests for this class
- Added new Service for BoardCards and tests for this class
- Updated BoardCardDto with new field orderNumber, added validation for this field and for cardText

2022-03-14 07:02 UTC, Szachista approved these changes

2022-03-14 09:35 UTC, patrykzawadzkiintive requested changes

2022-03-14 09:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardDto.java
> +    Integer orderNumber;
Hmm can you call that coulmnId?

2022-03-14 09:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardDto.java
> +                .orderNumber(boardCard.getColumn().getOrderNumber())
Can you use here instead of getOrderNumber() -> getColumnId()?

2022-03-14 09:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardsColumn.java
>      private final int orderNumber;
Can you rename that to columnId?

2022-03-14 09:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +@RequestMapping(value = "/api/v1/cards/boards", produces = MediaType.APPLICATION_JSON_VALUE)
Can you change that api/v1/cards/boards to api/v1/cards

2022-03-14 09:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +    @PostMapping("/{id}")
Add /boards here `/boards/{id}`

2022-03-14 10:58 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardsColumn.java
> +            case 0:
I didn't look at the whole code. Can we use enum with values?
E.g:
public enum BoardCardsColumn{
                SUCCESS(0)
                ...

2022-03-14 13:11 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardDto.java
> +    Integer orderNumber;
done

2022-03-14 13:11 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardDto.java
> +                .orderNumber(boardCard.getColumn().getOrderNumber())
done

2022-03-14 13:11 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardsColumn.java
>      private final int orderNumber;
done

2022-03-14 13:11 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +@RequestMapping(value = "/api/v1/cards/boards", produces = MediaType.APPLICATION_JSON_VALUE)
done

2022-03-14 13:11 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +    @PostMapping("/{id}")
done

2022-03-14 23:28 UTC, golldfish approved these changes

2022-03-15 12:08 UTC, daniel-kmiecik approved these changes

2022-03-15 12:15 UTC, merged