Search user by email
intive/patronage22-java-szczecin pull request #56
Opened 2022-03-14 17:03 UTC by MaciejJ0

2022-03-14 18:59 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers(URL_REGISTER, URL_LOGIN, "/api/v1/users/search",
should this endpoint be public?

2022-03-14 18:59 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/SearchEmailResponseDto.java
> +
empty line

2022-03-14 18:59 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/SearchEmailResponseDto.java
> +
empty line

2022-03-14 19:09 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +    }
Maybe we could consider checking what will happend if the email is null or blank?

2022-03-14 19:12 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers(URL_REGISTER, URL_LOGIN, "/api/v1/users/search",
No, private.

2022-03-14 19:13 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +    void searchShouldReturnOkWhenEmailsIsShorterThat64() throws Exception {
There's a typo in "than"

2022-03-14 19:14 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/UserServiceTest.java
> +    void searchShouldReturnListWithEmailsWhenEmailIsLongerThat3() {
There's a typo in "than"

2022-03-14 19:14 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/UserServiceTest.java
> +    void searchShouldReturnEmptyListWhenEmailIsShorterThat3() {
There's a typo in "than"

2022-03-14 19:28 UTC, patrykzawadzkiintive requested changes

2022-03-14 19:28 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/UserController.java
> +    public SearchEmailResponseDto search(@RequestParam @Size(max = 64) final String email) {
Hmmm... Maybe add here min 3 characters validation. Then update jira desceiption.

2022-03-14 19:28 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +    void searchShouldReturnBadRequestWhenEmailIsNotValid() throws Exception {
Is more than 64 characters

2022-03-14 19:28 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/SearchEmailResponseDto.java
> +public class SearchEmailResponseDto {
I think this dto is unne esary, you should return just List<String> ["email","email1"], with this dto you are returning {"email":["email","email1"]}

2022-03-15 12:41 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/UserServiceTest.java
> +    void searchShouldReturnListWithEmailsWhenEmailIsLongerThat3() {
Actually "size is longer than 2" or "has at least 3 characters" ("longer than 3" means "> 3"). Also "query" rather than "email" is more appropriate (IMO).

2022-03-15 12:41 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +    void searchShouldReturnOkWhenEmailsIsShorterThat64() throws Exception {
Isn't this test duplicated by _searchShouldReturnListWithEmailsWhenEmailIsLongerThat3_? Both tests check behaviour when input is correct.

2022-03-15 20:50 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/security/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers(URL_REGISTER, URL_LOGIN, "/api/v1/users/search",
my mistake

2022-03-15 20:52 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/SearchEmailResponseDto.java
> +
line deleted

2022-03-15 20:52 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/SearchEmailResponseDto.java
> +
line deleted

2022-03-15 20:54 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +    void searchShouldReturnOkWhenEmailsIsShorterThat64() throws Exception {
corrected

2022-03-15 20:54 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/UserServiceTest.java
> +    void searchShouldReturnListWithEmailsWhenEmailIsLongerThat3() {
corrected

2022-03-15 20:54 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/UserServiceTest.java
> +    void searchShouldReturnEmptyListWhenEmailIsShorterThat3() {
corrected

2022-03-15 20:54 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/UserControllerTest.java
> +    void searchShouldReturnBadRequestWhenEmailIsNotValid() throws Exception {
corrected

2022-03-15 20:55 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/SearchEmailResponseDto.java
> +public class SearchEmailResponseDto {
done

2022-03-16 07:50 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/UserController.java
> +    @GetMapping(value = "/users/search")
/users is enough in the path
https://www.javadevjournal.com/spring/rest-resource-naming/

2022-03-16 07:53 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/UserService.java
> +                .map(x -> x.getEmail())
Try to use more intuitive name in a lambda function, e.g. "u" or "user" instead of x

2022-03-16 09:30 UTC, Szachista approved these changes

2022-03-16 16:38 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/UserController.java
> +    @GetMapping(value = "/users/search")
done

2022-03-16 16:38 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/UserService.java
> +                .map(x -> x.getEmail())
done

2022-03-16 17:51 UTC, Szachista approved these changes

2022-03-16 18:30 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/UserController.java
> +                       @ApiResponse(responseCode = "400", description = "Email length is wrong")})
I'd change desc to Incorrect email's length

2022-03-16 19:51 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/UserController.java
> +                       @ApiResponse(responseCode = "400", description = "Email length is wrong")})
corrected

2022-03-16 22:57 UTC, edych approved these changes

2022-03-17 07:08 UTC, Radenzvous approved these changes

2022-03-17 08:19 UTC, patrykzawadzkiintive requested changes

2022-03-17 08:19 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/repository/UserRepository.java
> +    List<User> findAllByEmailContaining(final String email);
Maybe you could think about returning here just List<String> containing emails. You could use [JPQ](https://www.baeldung.com/spring-data-jpa-query). This will improve performance of the query and reduce amount of memory used by that query.

2022-03-17 14:15 UTC, daniel-kmiecik approved these changes

2022-03-17 16:33 UTC, MaciejJ0 commented on src/main/java/com/intive/patronage22/szczecin/retroboard/repository/UserRepository.java
> +    List<User> findAllByEmailContaining(final String email);
done

2022-03-17 18:38 UTC, golldfish approved these changes

2022-03-18 10:37 UTC, patrykzawadzkiintive approved these changes

2022-03-18 19:25 UTC, merged