Add 'remove board card' functionality
intive/patronage22-java-szczecin pull request #58
Opened 2022-03-16 08:55 UTC by Szachista

2022-03-16 15:39 UTC, Radenzvous requested changes

2022-03-16 15:50 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +                    @ApiResponse(responseCode = "400", description = "Not board's owner or not card's owner "
Owner occurs twice. Perhaps "Not an owner of the board or the card"?

2022-03-16 18:26 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +            throw new BadRequestException("Not board's owner or card's owner");
I'd suggest changing BadRequestException message to the one in Jira -  User is not able to delete card

2022-03-16 18:26 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +            throw new BadRequestException("State of the board is not \"CREATED\"");
same as above, we don't need to provide information about board state/user state

2022-03-16 18:26 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCard boardCard = BoardCard.builder()
I'd suggest the same as @Radenzvous - move creating board card to separate method because it'll be used in different tests.

2022-03-16 18:48 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCard boardCard = BoardCard.builder()
There is _buildBoard_ method in the _BoardServiceTest_ class - it might be redundant to create the same method in this class, so what solution would be better? Creating class consisting of static methods?

2022-03-16 23:11 UTC, edych approved these changes

2022-03-17 07:18 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +            throw new BadRequestException("State of the board is not \"CREATED\"");
Done,

2022-03-17 07:18 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +            throw new BadRequestException("Not board's owner or card's owner");
Done.

2022-03-17 07:18 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +                    @ApiResponse(responseCode = "400", description = "Not board's owner or not card's owner "
Done.

2022-03-17 08:39 UTC, patrykzawadzkiintive requested changes

2022-03-17 08:39 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCard boardCard = BoardCard.builder()
From my perspective it's ok to have s buildBoard method duplicated in that test here. So you could easily copy it. It could be easil changed / modified then without affecting logic of same method in BoardServiceTest

2022-03-17 08:39 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        when(boardCardsRepository.findById(cardId)).thenThrow(NotFoundException.class);
Your current implementation will call only bolded part
      **boardCardsRepository.findById(cardId)**
                .orElseThrow(() -> new NotFoundException("Card not found"));

It is throwing exception because of mock, not because of callling orElseThrow(). Please return null instead `when(boardCardsRepository.findById(cardId)).thenReturn(null);` and this test should pass theoretically.

2022-03-17 09:44 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        when(boardCardsRepository.findById(cardId)).thenThrow(NotFoundException.class);
_Optional.empty()_ instead of _null_ works.

2022-03-17 09:45 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCard boardCard = BoardCard.builder()
Done.

2022-03-17 09:45 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final Board board = Board.builder()
Done.

2022-03-17 10:15 UTC, Radenzvous approved these changes

2022-03-17 13:04 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +    public void removeCardFromTheBoard(final Integer cardId, final String email) {
Sufficient name for this method is just removeCard() (we know that card belongs to the board).

2022-03-17 18:13 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        if (boardCard.getBoard().getState().compareTo(EnumStateDto.CREATED) != 0)
Changed.

2022-03-17 18:14 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +    public void removeCardFromTheBoard(final Integer cardId, final String email) {
Done.

2022-03-17 19:51 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +
empty line

2022-03-17 19:53 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +
empty line

2022-03-17 19:58 UTC, golldfish commented
Besides - I think you should add at least one test in controller eg. happy path (200 when user deletes card from board).

2022-03-17 20:06 UTC, Szachista commented
> 

Operation _deleteBoard_ in the _BoardController_ class wasn't tested, so I thought only service layer (in case of delete request) should be tested.

2022-03-18 08:15 UTC, daniel-kmiecik approved these changes

2022-03-18 10:39 UTC, patrykzawadzkiintive approved these changes

2022-03-18 10:51 UTC, merged