all-board-api-mock added with BoardController, BoardDTO and BoardService
intive/patronage22-java-szczecin pull request #6
Opened 2022-01-24 19:23 UTC by Radenzvous

- Added BoardController, BoardDTO and BoardService
- Mocking 2 hardcoded objects
- GET /boards will show the objects

2022-01-25 07:51 UTC, MaciejJ0 approved these changes

2022-01-25 11:27 UTC, Szachista approved these changes

2022-01-25 13:33 UTC, patrykzawadzkiintive requested changes

2022-01-25 13:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDTO.java
> +    public enum State {
Please move that enum to separate enum class.

2022-01-25 13:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardDTO.java
> +public class BoardDTO {
Rename class to BoardDto -> lets follow camelCase naming system.

2022-01-25 13:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +package com.intive.patronage22.szczecin.retroboard.service;
Something is wrong with class formatting. Please also do not leave so many empty spaces. In intelij open class click on top bar Code -> Reformat Code. It should reformat it automatically.

2022-01-25 13:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +@GetMapping
Classs formatting.

2022-01-25 13:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/RetroboardApplication.java
> -
Unnecessary change.

2022-01-25 13:34 UTC, patrykzawadzkiintive commented
Please also add unit test and/or integration test for Controller class.

2022-01-26 17:45 UTC, patrykzawadzkiintive approved these changes

2022-01-26 17:49 UTC, golldfish approved these changes

2022-01-26 17:51 UTC, merged