Voting functionality  remove vote
intive/patronage22-java-szczecin pull request #65
Opened 2022-03-19 23:29 UTC by msperski

2022-03-21 07:09 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        when(boardCardsVotesRepository.getVotesByBoardAndUser(board, user)).thenReturn(
you don't need those methods if you're checking boardRepositoy.findById - they will not be used

2022-03-21 07:09 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        when(boardRepository.findById(card.getBoard().getId())).thenReturn(Optional.of(board));
same as above

If you want to check whether card is not found then you need to return user form userRepository and return from boardCardsRespository Optional.empty()
Exceptions are thrown in the order from your method

2022-03-21 07:09 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        when(boardCardsVotesRepository.findByCardAndVoter(card, user)).thenReturn(Optional.of(boardCardVotes));
same as above

2022-03-21 07:09 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        assertEquals(remainingUserVotes, 0);
You don't check whether exception will be thrown. You should call method and then assert method result to excpected results.

2022-03-21 07:09 UTC, golldfish commented
Also there's no test for contoller. You should check at least happy path (200)

2022-03-21 07:22 UTC, golldfish requested changes

2022-03-21 07:22 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        assertEquals(remainingUserVotes, 0);
You don't check whether exception will be thrown. You on;y check whether value of variable has changed 
You should call method and then assert method result to excpected results.

2022-03-21 07:29 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        vote.setVotes(vote.getVotes() - 1);
yes , if one then remove entry, we should not allow to save votes enity with number of vote <= 0

2022-03-21 07:42 UTC, patrykzawadzkiintive requested changes
Also all comments from @golldfish

2022-03-21 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        final Board board = boardRepository.findById(card.getBoard().getId())
This check is not required , there is one to many relationship validated on db level, this case will never happen. if there is a card assigned to the board, then board will always exist.

2022-03-21 07:42 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        if (!board.getUsers().contains(user) && !board.getCreator().equals(user)) {
in that case, board could be taken from card.getBoard()

2022-03-21 07:45 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final Map<String, Integer> remainingVotesMap = boardCardService.addVote(cardId, email);
I guess method `removeVote` wasn't called in this test

2022-03-22 13:33 UTC, patrykzawadzkiintive requested changes

2022-03-22 13:33 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardController.java
> +    @DeleteMapping("/{id}/votes/delete")
There is no sense to add /delete when you are using http DELETE method. Can you remove that + update the jira description.

2022-03-22 13:33 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardControllerTest.java
> +    void removeVoteShouldThrowBadRequest(final String exceptionMessage) throws Exception {
removeVoteShouldThrowException

2022-03-23 10:40 UTC, edych commented
Hey, could you consider to give a resolve to the conversations you've already included in the latest commit? IMO it would make it easier to find the things we still need to check. Thank you :blush:

2022-03-23 12:43 UTC, patrykzawadzkiintive approved these changes

2022-03-23 12:46 UTC, edych approved these changes

2022-03-23 12:47 UTC, patrykzawadzkiintive requested changes

2022-03-23 12:47 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        assertEquals(3,boardCardVotes.getVotes());
You are not checking the method resposne here, but object created in test.

Change that to:
assertEquals(removeVote.get("remainingVotes"),3);

2022-03-23 12:47 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        assertEquals(0, boardCardVotes.getVotes());
You are not checking the method resposne here, but object created in test.
Verify numberOfVotes returned by this method  boardCardService.removeVote(cardId, email);

2022-03-23 12:47 UTC, patrykzawadzkiintive requested changes

2022-03-23 12:47 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        if (vote.getVotes()==0) {
(vote.getVotes() == 0)

2022-03-23 14:50 UTC, daniel-kmiecik commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +
I think it would be more sufficient when you try to do something like this:
if ((vote.getVotes()-1) == 0) { - here is no need to save vote, just delete
} else {
}
return Map.of("remainingVotes", vote.getVotes());

2022-03-23 15:12 UTC, msperski commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +
Shouldn't it be `if (vote.getVotes() == 0)`?

2022-03-23 15:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    @DisplayName("Remove vote should throw not found when user is not assigned to board")
You're not throwing not found here

2022-03-23 15:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    @DisplayName("Remove vote should throw bad request when card is not found")
You're throwing not found, not bad request

2022-03-23 21:22 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +
I also think it should be `if ((vote.getVotes()-1) == 0)` because if there is only one vote left to remove there is no need to `setVotes` because we are going to delete it anyway, so with this solution, we could move setting votes into the else section

2022-03-24 07:21 UTC, patrykzawadzkiintive approved these changes

2022-03-24 12:13 UTC, Radenzvous approved these changes

2022-03-24 17:19 UTC, golldfish approved these changes

2022-03-24 17:20 UTC, merged