P2022-1511 - Next Step implementation
intive/patronage22-java-szczecin pull request #66
Opened 2022-03-21 11:16 UTC by Radenzvous

Adding nextState api call which should allow board owner to change board state up to "DONE" state.

2022-03-21 12:11 UTC, golldfish commented
Also I think you should add at least one test for controller class (eg. happy path 200)

2022-03-21 12:12 UTC, golldfish requested changes

2022-03-21 12:12 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        if (board.getState() == EnumStateDto.DONE) {
I think you should change it to: `if(EnumStateDto.DONE.equals(board.getState()) {`

2022-03-21 12:12 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        assignedUsersDtoList.add(UserDto.createFrom(user));
I think that user(creator) is already added to board.users. Are you sure you're not returing this data twice?

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    @DisplayName("When nextState is used - it will change state from Created to next state which is Voting and saves board details.")
I'd change it to: "When nextState is used - it will change state from Created to Voting (next) and save board details.")

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
empty line

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
empty line

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
i think that you should also retrun ` when(boardRepository.findById(board.getId())).thenReturn(Optional.empty());` because i'm not sure whether it's returning proper not found exception

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
empty line

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
empty line

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var user1 = new User(uid1, email1, "displayName", Set.of(), Set.of());
Could you rename user1/user2 to owner/user? It will make this test more readable

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
empty line

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        when(userRepository.findUserByEmail(email2)).thenReturn(Optional.of(user2));
I think that only `when(userRepository.findUserByEmail(email2)).thenReturn(Optional.of(user2));` will be enough for this test

2022-03-21 12:12 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var board = buildBoard(user, EnumStateDto.CREATED, 10, Set.of());
you can create board with 0 votes and there's no need to set them later.

2022-03-21 16:30 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +        return boardService.nextState(id, authentication.getName());}
Missing new line before closing curly brace.

2022-03-21 16:30 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +            BoardDto.fromModel(boardRepository.save(board));
Is it necessary to call _BoardDto.fromModel()_? Result of that method is not assigned to any variable.

2022-03-22 13:03 UTC, patrykzawadzkiintive requested changes

2022-03-22 13:03 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
nextStateChangeStateValueAndSaveTheData() -> first we change the state then we save the data

2022-03-22 13:03 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    @DisplayName("When nextState on a board which maximumNumberOfVotes is set to 0 - Bad Request Exception is thrown.")
When nextState() is called on a board with maximumNumberOfVotes = 0 -> Bad Request Exception is thrown.

2022-03-22 20:37 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        if (board.getState() == EnumStateDto.DONE) {
According to the mentioned discussion "==" should be fine and it also makes sure the value is nonnull as an addition, I'll keep it if there are no other objections. Thank you.

2022-03-22 20:51 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        assignedUsersDtoList.add(UserDto.createFrom(user));
I am, however my jira task asks me to:
"Return same data as /api/v1/boards/{id}" so if I change it - it no longer matches that

2022-03-22 23:17 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        assignedUsersDtoList.add(UserDto.createFrom(user));
Yes but it still be the same data. In the assigned user - the creator data will appear one or many times when you go to next step?

2022-03-23 10:14 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/EnumStateDto.java
> +    private static final EnumStateDto[] vals = values();
This entire part of the code was replaced.

2022-03-23 10:15 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        if (board.getMaximumNumberOfVotes() == 0){
Thank you, done.

2022-03-23 10:15 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        }else {
Done

2022-03-23 10:17 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    @DisplayName("When nextState is used - it will change state from Created to next state which is Voting and saves board details.")
Thank you, fixed.

2022-03-23 10:17 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Thank you, both corrected.

2022-03-23 10:18 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Corrected.

2022-03-23 10:41 UTC, edych commented
Hey, could you consider to give a resolve to the conversations you've already included in the latest commit? IMO it would make it easier to find the things we still need to check. Thank you :blush:

2022-03-23 11:11 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Added

2022-03-23 11:11 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Corrected

2022-03-23 11:11 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Corrected

2022-03-23 11:12 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var user1 = new User(uid1, email1, "displayName", Set.of(), Set.of());
Owner and user are now the names of variables

2022-03-23 11:12 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +
Done

2022-03-23 11:14 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        when(userRepository.findUserByEmail(email2)).thenReturn(Optional.of(user2));
modified so that only 
when(boardRepository.findById(board.getId())).thenReturn(Optional.of(board));
        when(userRepository.findUserByEmail(email2)).thenReturn(Optional.of(user));
        are included

2022-03-23 11:14 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final var board = buildBoard(user, EnumStateDto.CREATED, 10, Set.of());
Modified boardBuilder arguments

2022-03-23 11:15 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +        return boardService.nextState(id, authentication.getName());}
Corrected

2022-03-23 11:16 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +            BoardDto.fromModel(boardRepository.save(board));
Thank you, corrected

2022-03-23 11:17 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/EnumStateDto.java
> +    private static final EnumStateDto[] vals = values();
The entire logic was completely replaced now with a unit test added and values assigned to states of enum

2022-03-23 11:17 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/EnumStateDto.java
> +        return vals[(this.ordinal()+1)];
validation added, test added

2022-03-23 11:18 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    @DisplayName("When nextState on a board which maximumNumberOfVotes is set to 0 - Bad Request Exception is thrown.")
Corrected, thank you.

2022-03-23 11:22 UTC, Radenzvous commented
> Hey, could you consider to give a resolve to the conversations you've already included in the latest commit? IMO it would make it easier to find the things we still need to check 😊

Question - should I resolve what was asked for or should it be done by the person that requested changes / added comment? If my proposed solution still does not meet the expectations somehow - it could continue on there.

2022-03-23 12:35 UTC, patrykzawadzkiintive requested changes

2022-03-23 12:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final List<BoardCardsColumnDto> boardCardsColumnDtos =
Instead of duplicating the logic, extract the part used by this method and by getBoardDataById() to separate method. Because of that in case of any update in the future this method will be also updated, and you don't need to verify if logic to create BoardDataDto is correct.

2022-03-23 12:38 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        if (board.getState() == EnumStateDto.DONE) {
Please change that to equals, comparing with == is not good practice , and always cause problems.

2022-03-23 14:45 UTC, Radenzvous commented
> Also I think you should add at least one test for controller class (eg. happy path 200)

Added test for happy path, thank you.

2022-03-23 15:21 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +    public BoardDataDto nextState (final Integer boardId, final String email) {
Would setNextState be more readable? It cycles through enumState of the board moving to the next state each time it is used, then returns boardData

2022-03-23 15:24 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/EnumStateDto.java
> +
Empty lines

2022-03-23 15:24 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    private Board buildBoard(final User user, final EnumStateDto state, final int id, final Set<User> users, final Integer maximumNumberOfVotes) {
Can you switch order of arguments? So they will be in the same order as we use them in builder? I think it would be easier to read and use but it's just an idea

2022-03-23 15:24 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +                NotFoundException.class, () -> boardService.nextState(1,email));
Change 1 to board_id

2022-03-23 17:33 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    private Board buildBoard(final User user, final EnumStateDto state, final int id, final Set<User> users, final Integer maximumNumberOfVotes) {
Changed the order of arguments in all tests in BoardServiceTest

2022-03-23 17:33 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +                NotFoundException.class, () -> boardService.nextState(1,email));
done

2022-03-23 17:33 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/EnumStateDto.java
> +
done

2022-03-24 07:21 UTC, patrykzawadzkiintive approved these changes

2022-03-24 07:21 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final List<BoardCardsColumnDto> boardCardsColumnDtos =
I would call that prepareBoardData()

2022-03-24 12:10 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +        final List<BoardCardsColumnDto> boardCardsColumnDtos =
this is renamed now

2022-03-24 12:11 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardService.java
> +    public BoardDataDto nextState (final Integer boardId, final String email) {
Changed to setNextState

2022-03-24 14:00 UTC, edych approved these changes

2022-03-24 17:12 UTC, msperski approved these changes

2022-03-24 17:16 UTC, golldfish approved these changes

2022-03-25 08:23 UTC, Szachista approved these changes
Inconsistent use of _var_ keyword in tests.

2022-03-25 10:31 UTC, merged