P2022-1885 sort board by id
intive/patronage22-java-szczecin pull request #67
Opened 2022-03-25 18:19 UTC by MaciejJ0

2022-03-25 19:17 UTC, edych commented
I think you could consider adding a test checking if returned Boards are sorted in descending order

2022-03-25 19:54 UTC, patrykzawadzkiintive requested changes
Unit test is required

2022-03-25 19:54 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                .sorted(Comparator.comparingLong(BoardDto::getId).reversed())
Yes logic should be placed in sevice class.

2022-03-27 14:00 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
>          final Board board = Board.builder()
Please use the board builder that was taken outside in this class instead of creating board builder each time you are building a board.

Example:
`final var board = buildBoard(10,EnumStateDto.CREATED, user, Set.of(),0);`

2022-03-27 14:37 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void getUserBoardsShouldReturnSortedListByIdWhenUserExist() {
Exists*

2022-03-29 17:57 UTC, patrykzawadzkiintive approved these changes

2022-03-29 18:01 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void getUserBoardsShouldReturnSortedListByIdWhenUserExist() {
Interesting, i didn't know that.
 https://ell.stackexchange.com/questions/128807/exist-or-exists#:~:text=where%20exists%20is%20the%20verb.&text=is%20not%20useful-,Show%20activity%20on%20this%20post.,s%20or%20es%20is%20used.

2022-03-29 19:57 UTC, edych approved these changes

2022-03-29 20:24 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final Board board1 = Board.builder()
Please use existing method to create board

2022-03-30 12:04 UTC, patrykzawadzkiintive commented
Solve all comments mentioned by others before merge.

2022-03-30 16:18 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +    void getUserBoardsShouldReturnSortedListByIdWhenUserExist() {
done

2022-03-30 16:18 UTC, MaciejJ0 commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardServiceTest.java
> +        final Board board1 = Board.builder()
done

2022-03-30 17:09 UTC, golldfish approved these changes

2022-03-30 19:32 UTC, Radenzvous approved these changes

2022-03-30 21:16 UTC, merged