P2022 1769 add action to the card
intive/patronage22-java-szczecin pull request #71
Opened 2022-04-02 07:25 UTC by Radenzvous

2022-04-02 08:35 UTC, patrykzawadzkiintive requested changes

2022-04-02 08:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/controller/BoardController.java
> +                                                     final Authentication authentication) {
Try to revert unnecesary formating changes.

2022-04-02 08:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardsColumn.java
> +
Try to avpid unnecesary formatting changes. Can you revert that?

2022-04-02 08:35 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        final Board board = boardRepository.findById(card.getBoard().getId())
Loading board is not required here, you could do card.getBoard() BoardNotFound exception will be never thrown because there is validation for that relationship on db level. Each card must be assigmed to the board.

2022-04-02 08:46 UTC, golldfish commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardActionRequestDto.java
> +}
Is it necessary to create another dto for just request? I think we can use BoardCardActionDto.java and only pass text during request.

2022-04-02 08:46 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardControllerTest.java
> +        when(boardCardService.addCardAction(cardId, email, cardActionText)).thenReturn(null);
why are you returning null? It's "happy path" so I think that this method should return BoardCardActionDto and then hcheck whether correct data is returned after endpoint call.

2022-04-02 08:46 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    @DisplayName("When addCardAction() is called and the user is not found -> User not found Exception is thrown.")
Not found exception is thrown

2022-04-02 17:55 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardActionRequestDto.java
> +}
Hmmm good point. And you could set @length on boardCardActionDto.class and it should work with validation correctly

2022-04-04 17:54 UTC, Radenzvous commented on src/main/java/com/intive/patronage22/szczecin/retroboard/dto/BoardCardActionRequestDto.java
> +}
I noticed that being done in another call and noticed that then swagger shows entire DTO and not just the desired field. Is that your expected result or am I missing something?

2022-04-05 15:32 UTC, patrykzawadzkiintive approved these changes

2022-04-05 16:31 UTC, Szachista approved these changes

2022-04-05 18:50 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardControllerTest.java
> +        when(boardCardService.addCardAction(cardId, email, cardActionText)).thenReturn(null);
done

2022-04-05 19:00 UTC, Radenzvous commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    @DisplayName("When addCardAction() is called and the user is not found -> User not found Exception is thrown.")
done

2022-04-05 19:43 UTC, merged