Add "remove action" functionality
intive/patronage22-java-szczecin pull request #72
Opened 2022-04-04 09:24 UTC by Szachista

2022-04-04 09:47 UTC, edych commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        boardCardService.removeAction(actionId, email);
Maybe you could consider adding an ArgumentCaptor to check the value passed to the method `boardCardsActionsRepository.deleteById(captor.capture())`

2022-04-04 09:54 UTC, edych commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        if (!EnumStateDto.ACTIONS.equals(boardCardAction.getCard().getBoard().getState()))
I think It would be more readable to throw a different message when it comes to Board state, for example, "Board state is not ACTIONS"

2022-04-04 09:58 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +        if (!EnumStateDto.ACTIONS.equals(boardCardAction.getCard().getBoard().getState()))
I was thinking about avoiding verbose messages (as it was mentioned earlier). I'll change it.

2022-04-04 10:20 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        boardCardService.removeAction(actionId, email);
Done.

2022-04-04 10:30 UTC, edych approved these changes

2022-04-04 11:38 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCardAction action = new BoardCardAction(actionId, boardCard, "sometext");
Maybe it's worth to check case when action is actually added to board card and whether it's removed from board card after deleting

2022-04-04 11:38 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenUserTriesToRemoveExistingActionInRightBoardsState() {
I'd change it to _removeQctionShouldFailWhenUserIsNotOwner_

2022-04-04 11:38 UTC, golldfish commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenUserTriesToRemoveExistingActionInWrongBoardsState() {
The test is the same as above. It'll never check the state of board, because first it'll check board ownership and the exception will always be thrown when user is not owner

2022-04-04 12:32 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenUserTriesToRemoveExistingActionInRightBoardsState() {
removeActionShouldFailWhenBoardStateIsNotActions

2022-04-04 12:33 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenUserTriesToRemoveExistingActionInWrongBoardsState() {
removeActionShouldFailWhenBoardStateIsNotActions

2022-04-04 12:41 UTC, patrykzawadzkiintive requested changes

2022-04-04 12:41 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +            throw new BadRequestException("Not your board");
You are not the board owner.

2022-04-04 12:41 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardControllerTest.java
> +    void removeActionShouldPassInHappyPath() throws Exception {
removeActionShouldReturnOk

2022-04-04 12:41 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldPassWhenOwnerTriesToRemoveExistingActionInRightBoardsState() {
removeActionShouldPassWhenOwnerTriesToRemoveExistingActionWhenBoardStateActions

2022-04-04 12:41 UTC, patrykzawadzkiintive commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenOwnerTriesToRemoveExistingActionInWrongBoardsState() {
*ExistingActionWhenBoardStateIsNotActions

2022-04-04 12:55 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCardAction action = new BoardCardAction(actionId, boardCard, "sometext");
But how to achieve this goal in the mock environment?

2022-04-05 05:56 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +        final BoardCardAction action = new BoardCardAction(actionId, boardCard, "sometext");
Discussed this issue with Patryk - it's unfeasible in this case.

2022-04-05 05:56 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenUserTriesToRemoveExistingActionInRightBoardsState() {
Done.

2022-04-05 05:56 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenUserTriesToRemoveExistingActionInWrongBoardsState() {
Corrected.

2022-04-05 05:56 UTC, Szachista commented on src/main/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardService.java
> +            throw new BadRequestException("Not your board");
Done.

2022-04-05 05:56 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/controller/BoardCardControllerTest.java
> +    void removeActionShouldPassInHappyPath() throws Exception {
Done.

2022-04-05 05:56 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldPassWhenOwnerTriesToRemoveExistingActionInRightBoardsState() {
Done.

2022-04-05 05:58 UTC, Szachista commented on src/test/java/com/intive/patronage22/szczecin/retroboard/service/BoardCardServiceTest.java
> +    void removeActionShouldFailWhenOwnerTriesToRemoveExistingActionInWrongBoardsState() {
Corrected using @golldfish's suggestion.

2022-04-05 15:32 UTC, patrykzawadzkiintive approved these changes

2022-04-05 15:58 UTC, MaciejJ0 approved these changes

2022-04-05 16:32 UTC, merged