Flyway integration
intive/patronage22-java-szczecin pull request #9
Opened 2022-01-24 20:00 UTC by golldfish

2022-01-25 08:02 UTC, MaciejJ0 commented
I would change the file format from "application.properties" to "application.yaml"

2022-01-25 12:20 UTC, golldfish commented
> I would change the file format from "application.properties" to "application.yaml"

Why? Could you provide some advantages of this solution please?

2022-01-25 12:56 UTC, patrykzawadzkiintive requested changes

2022-01-25 12:56 UTC, patrykzawadzkiintive commented on src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/flyway.conf
> +flyway.user=admin
Can you move properties to application.properties 
spring.flyway.baseline-on-migrate = true
spring.flyway.encoding = UTF-8
spring.flyway.url  = ${spring.datasource.url}
spring.flyway.user = ${spring.datasource.username}
spring.flyway.password = ${spring.datasource.password}
spring.flyway.table=schema_version
spring.flyway.clean-disabled = true

Then remove that config file.

2022-01-25 12:56 UTC, patrykzawadzkiintive commented on pom.xml
> +		<flyway.configFiles>src/main/java/com/intive/patronage22/szczecin/retroboard/configuration/flyway.conf</flyway.configFiles>
This line could be removed if config is in properties file.

2022-01-25 12:58 UTC, patrykzawadzkiintive commented
> 

It's up to you how you store properties, whether .properties or .yaml but keep on solution for whole project.

2022-01-25 14:56 UTC, daniel-kmiecik commented on README.md
> +###Flyway
There is no need to do this commands manually. Spring Boot will automatically find the script and run it when the application starts.

2022-01-25 16:00 UTC, MaciejJ0 approved these changes

2022-01-25 20:53 UTC, golldfish commented on README.md
> +###Flyway
Thanks, I will remove them in next fix.

2022-01-26 07:33 UTC, Szachista approved these changes

2022-01-26 07:50 UTC, daniel-kmiecik approved these changes

2022-01-26 09:08 UTC, edych approved these changes

2022-01-26 10:19 UTC, patrykzawadzkiintive approved these changes

2022-01-26 11:20 UTC, merged